"""add new colomns

Revision ID: 317e48a859ad
Revises: 610c13d0222d
Create Date: 2021-08-28 17:58:00.723403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '317e48a859ad'
down_revision = '610c13d0222d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address_info', sa.Column('edit', sa.Boolean(), nullable=True))
    op.add_column('address_info', sa.Column('uncertain', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_address_info_edit'), 'address_info', ['edit'], unique=False)
    op.create_index(op.f('ix_address_info_uncertain'), 'address_info', ['uncertain'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_address_info_uncertain'), table_name='address_info')
    op.drop_index(op.f('ix_address_info_edit'), table_name='address_info')
    op.drop_column('address_info', 'uncertain')
    op.drop_column('address_info', 'edit')
    # ### end Alembic commands ###
