"""create table

Revision ID: 610c13d0222d
Revises: 
Create Date: 2021-08-27 10:06:07.606364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '610c13d0222d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('annotations', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_info_address'), 'address_info', ['address'], unique=True)
    op.create_index(op.f('ix_address_info_annotations'), 'address_info', ['annotations'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_address_info_annotations'), table_name='address_info')
    op.drop_index(op.f('ix_address_info_address'), table_name='address_info')
    op.drop_table('address_info')
    # ### end Alembic commands ###
