"""change unique

Revision ID: bb0309ef3c1f
Revises: 317e48a859ad
Create Date: 2021-09-06 13:51:49.551688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb0309ef3c1f'
down_revision = '317e48a859ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_address_info_address', table_name='address_info')
    op.create_index(op.f('ix_address_info_address'), 'address_info', ['address'], unique=False)
    op.drop_index('ix_address_info_annotations', table_name='address_info')
    op.create_index(op.f('ix_address_info_annotations'), 'address_info', ['annotations'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_address_info_annotations'), table_name='address_info')
    op.create_index('ix_address_info_annotations', 'address_info', ['annotations'], unique=False)
    op.drop_index(op.f('ix_address_info_address'), table_name='address_info')
    op.create_index('ix_address_info_address', 'address_info', ['address'], unique=False)
    # ### end Alembic commands ###
